e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homeapp.urls')),
    path('', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),  
]

if settings.DEBUG:
    #urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_commerce/homeapp/urls.py
from django.urls import path
from .views import homepage

app_name ="homeapp"

urlpatterns = [
    path('', homepage, name='homepage'),      
] 

e_commerce/products/urls.py
from django.urls import path
from .views import all_products,product_details,updateItem,cart,add_product,edit_product,category,checkout

app_name ="products"

urlpatterns = [
    path('shop/', all_products, name='productPage'), 
    path('update_item/', updateItem, name="update_item"),
    path('cart/', cart, name="cart_page"),
    path('product_details/<int:pk>/',product_details , name='product_details'),  

    path('add_product/', add_product, name="add_product_page"),  
    path('edit-product/<int:pk>/', edit_product, name='edit_product'),

    path('category/<int:pk>/', category, name='category_products'),

    path('checkout/', checkout, name="checkout"),
]  

e_commerce/users/urls.py
from django.urls import path
from users.views import RegisterView,LogInView,LogOutView,userProfile

app_name ="users"

urlpatterns = [
    path('login/', LogInView, name='loginPage'),  
    path('sign-up/', RegisterView, name='registerPage'),
    # path('sign-out/', LogOutView.as_view(), name='logoutPage'),
    path('sign-out/', LogOutView, name='logoutPage'),
    path('my-profile/', userProfile, name='profilePage'),
] 

e_commerce/homeapp/models.py
from django.db import models

# Create your models here.
class Slider(models.Model):
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='slider_img')

e_commerce/homeapp/views.py
from django.shortcuts import render
from products.models import Product,Category
from .models import Slider
# Create your views here.

def homepage(request):
    all_slider = Slider.objects.all()  
    products = Product.objects.filter(is_verified=True)
    categories = Category.objects.all()  
    context = {
    'all_slider':all_slider,
    'products':products,
    'categories':categories
    }
    return render(request,'homeapp/index.html',context)

def success(request):
    return render(request,'homeapp/success.html')

e_commerce/templates/homeapp/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main id="main">
    <div class="container">

        <!--MAIN SLIDE-->
        <div class="wrap-main-slide">
            <div class="slide-carousel owl-carousel style-nav-1" data-items="1" data-loop="1" data-nav="true" data-dots="false">
               
     
        {% for slider in all_slider %}
                <div class="item-slide">
                    <img src="{{slider.image.url}}" alt="" class="img-slide">
                    {% comment %} <div class="slide-info slide-2">
                        <h2 class="f-title">Extra 25% Off</h2>
                        <span class="f-subtitle">On online payments</span>
                        <p class="discount-code">Use Code: #FA6868</p>
                        <h4 class="s-title">Get Free</h4>
                        <p class="s-subtitle">TRansparent Bra Straps</p>
                    </div> {% endcomment %}
                </div>
        {% endfor %}
           


            </div>
        </div>

        <!--BANNER-->
        <div class="wrap-banner style-twin-default">
            <div class="banner-item">
                <a href="#" class="link-banner banner-effect-1">
                    <figure><img src="{% static 'images/home-1-banner-1.jpg' %}" alt="" width="580" height="190"></figure>
                </a>
            </div>
            <div class="banner-item">
                <a href="#" class="link-banner banner-effect-1">
                    <figure><img src="{% static 'images/home-1-banner-2.jpg' %}" alt="" width="580" height="190"></figure>
                </a>
            </div>
        </div>


        <!--Latest Products-->
        <div class="wrap-show-advance-info-box style-1">
            <h3 class="title-box">Latest Products</h3>
            <div class="wrap-top-banner">
                <a href="#" class="link-banner banner-effect-2">
                    <figure><img src="{% static 'images/digital-electronic-banner.jpg' %}" width="1170" height="240" alt=""></figure>
                </a>
            </div>
            <div class="wrap-products">
                <div class="wrap-product-tab tab-style-1">						
                    <div class="tab-contents">
                        <div class="tab-content-item active" id="digital_1a">
                            <div class="wrap-products slide-carousel owl-carousel style-nav-1 equal-container" data-items="5" data-loop="false" data-nav="true" data-dots="false" data-responsive='{"0":{"items":"1"},"480":{"items":"2"},"768":{"items":"3"},"992":{"items":"4"},"1200":{"items":"5"}}' >

          
                                {% for product in products %}
                                <div class="product product-style-2 equal-elem ">
                                    <div class="product-thumnail">
                                        <a href="{% url 'products:product_details' product.pk %}" title="T-Shirt Raw Hem Organic Boro Constrast Denim">
                                            <figure><img src="{{product.image.url}}" width="800" height="800" alt="T-Shirt Raw Hem Organic Boro Constrast Denim"></figure>
                                        </a>
                                        <div class="group-flash"> 
                                            <span class="flash-item sale-label">sale</span>
                                        </div>
                                        <div class="wrap-btn">
                                            <a href="#" class="function-link">quick view</a>
                                        </div>
                                    </div> 
                                    <div class="product-info">
                                        <a href="{% url 'products:product_details' product.pk %}" class="product-name"><span>{{product.name}}</span></a>
                                        <div class="wrap-price"><ins><p class="product-price">${{product.price}}</p></ins> <del><p class="product-price">$250.00</p></del></div>
                                    </div>
                                </div>
                                {% endfor %}


                            </div>
                        </div>							
                    </div>
                </div>
            </div>
        </div>

        <!--Product Categories-->
        <div class="wrap-show-advance-info-box style-1">
            <h3 class="title-box">Product Categories</h3>
            <div class="wrap-top-banner">
                <a href="#" class="link-banner banner-effect-2">
                    <figure><img src="{% static 'images/fashion-accesories-banner.jpg' %}" width="1170" height="240" alt=""></figure>
                </a>
            </div>
         
        </div>		
        

    </div>

    <style>
        .box {
            box-shadow: 0px 10px 15px -3px rgba(0,0,0,0.1);
            min-height: 100px;
            background: #f3fee3;
            border-radius: 5px;
        };
        .box-warper{
            margin-left:5px;
        }
    </style>

     <!--Product Categories-->

     {% if categories %}
    <div class="container">
        <div class="row">

            {% for cat in categories %}
            <a class="box-warper" href= "{% url 'products:category_products' cat.pk %}">
            <div class="col-md-3 box">
                <h3 style="text-align: center;">{{cat.name}}</h3>
            </div>
            </a>
            {% endfor %}

        </div>
    </div>
    {% endif %}



</main>


{% endblock %}

e_commerce/templates/homeapp/success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!--main area-->
<main id="main" class="main-site">

    <div class="container">

        <div class="wrap-breadcrumb">
            <ul>
                <li class="item-link"><a href="#" class="link">home</a></li>
                <li class="item-link"><span>Thank You</span></li>
            </ul>
        </div>
    </div>
    
    <div class="container pb-60">
        <div class="row">
            <div class="col-md-12 text-center">
                <h2>Thank you for your order</h2>
                <p>A confirmation email was sent.</p>
                <a href="index.html" class="btn btn-submit btn-submitx">Continue Shopping</a>
            </div>
        </div>
    </div><!--end container-->

</main>
<!--main area-->

{% endblock %}