e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homeapp.urls')),
    path('', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),  
]

if settings.DEBUG:
    #urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_commerce/products/urls.py
from django.urls import path
from .views import all_products,product_details,updateItem,cart,add_product,edit_product,category,checkout

app_name ="products"

urlpatterns = [
    path('shop/', all_products, name='productPage'), 
    path('update_item/', updateItem, name="update_item"),
    path('cart/', cart, name="cart_page"),
    path('product_details/<int:pk>/',product_details , name='product_details'),  

    path('add_product/', add_product, name="add_product_page"),  
    path('edit-product/<int:pk>/', edit_product, name='edit_product'),

    path('category/<int:pk>/', category, name='category_products'),

    path('checkout/', checkout, name="checkout"),
]  

e_commerce/users/urls.py
from django.urls import path
from users.views import RegisterView,LogInView,LogOutView,userProfile

app_name ="users"

urlpatterns = [
    path('login/', LogInView, name='loginPage'),  
    path('sign-up/', RegisterView, name='registerPage'),
    # path('sign-out/', LogOutView.as_view(), name='logoutPage'),
    path('sign-out/', LogOutView, name='logoutPage'),
    path('my-profile/', userProfile, name='profilePage'),
] 

e_commerce/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# from django.utils.translation import ugettext_lazy as _

from django.core.validators import RegexValidator 
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from .manager import UserManager


class Accounts(AbstractUser):
    email = models.EmailField(_('email address'), unique = True)
    phone_regex = RegexValidator(regex=r'^(?:\+88|88)?(01[3-9]\d{8})$', message="Phone number must be entered in the format: '+8801XXXXXX'. Up to 14 digits allowed.")
    mobile_number = models.CharField(validators=[phone_regex], max_length=20, unique=True,null=True,blank=True)

    is_verified = models.BooleanField(
        _('verified'),
        default=False, 
        help_text=_(
            'Designates whether this user has been verified.'
            'Un-verified users cannot log in.'
        ),
    )

    is_saler = models.BooleanField(
        _('Saler Permission'),
        default=False,
        help_text=_(
            'Designates whether this user should be treated as founder.'
        ),
    )

    created_at = models.DateTimeField(default=now, editable=False)
    ##default
    profile_pic = models.FileField(upload_to='profile_pic',null=True,blank=True)
    address = models.TextField(null=True,blank=True)


    username = None
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()


    def __str__(self):
        return self.email

    # class Meta:
    #     verbose_name = 'User'
    #     verbose_name_plural = 'Users'

e_commerce/users/views.py
from django.http import HttpResponse
from users.models import Accounts
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login,logout

from django.views.generic import View
from orders.models import Order,OrderItem
from django.contrib.auth.decorators import login_required

def RegisterView(request):
    ''' Sign up new user to E-commerce '''
    if request.method == 'POST':

        email = request.POST.get('email')
        first_name = request.POST.get('firstname')
        last_name = request.POST.get('lastname')
        mobile_number= request.POST.get('mobilenumber')
        password = request.POST.get('password')
        repeatPassword = request.POST.get('confirmpassword') 


        if not (email and password and repeatPassword and last_name and mobile_number and first_name):
            messages.error(request, 'Please fillup all field correctly!!')
            return redirect('users:registerPage')

        if Accounts.objects.filter(email=email).exists():
            messages.info(request, 'Email already exists.')
            return redirect('users:registerPage')

        if Accounts.objects.filter(mobile_number=mobile_number).exists():
            messages.info(request, 'Mobile number already exists.')
            return redirect('users:registerPage')

        if password and repeatPassword:
            if password != repeatPassword:
                messages.warning(request, "The two password fields didn't match.")
                return redirect('users:registerPage')

        user = Accounts.objects.create_user( 
            email=email,
            first_name=first_name,
            last_name=last_name,
            mobile_number=mobile_number,
        )
        user.set_password(password)
        user.save()
        messages.success(request, "Your Account Is Successfully Created")
         #Successfully registered. Redirect to homepage
        return redirect('users:loginPage')
    return render(request, 'users/register.html')

def LogInView(request):
    ''' Sign in views '''
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        user = Accounts.objects.filter(email=email).first() 
        if user is None:
            messages.warning(request, '%s Not found!' % email) 
            return redirect('users:loginPage')

        if not (email and password):
            messages.error(request, 'Please provide all the details!!')
            return redirect('users:loginPage')

        profile = Accounts.objects.filter(email=user).first()

        ''' User verification checks '''
        if not profile.is_verified:
            messages.info(request, 'Your account is not verified!')
            return redirect('users:loginPage')

        if not profile.is_active:
            messages.info(request, 'Your account is not Active!')
            return redirect('users:loginPage')

        auth_user = authenticate(email=email, password=password)
        if auth_user is None:
            messages.warning(request, 'Wrong credentials')
            return redirect('users:loginPage')
        login(request, auth_user)
        return redirect('products:productPage')
    return render(request, 'users/login.html')



def LogOutView(request):
    logout(request)
    return redirect('users:loginPage') 


# customer = request.user.customer
# 		order, created = Order.objects.get_or_create(customer=customer, complete=False)
# 		items = order.orderitem_set.all()
# 		cartItems = order.get_cart_items

@login_required(login_url='users:loginPage')
def userProfile(request):
    vendor = request.user
    products = vendor.products.all() 
    order, created = Order.objects.get_or_create(customer=vendor)
    items = order.orderitem_set.all()

    return render(request,'users/profile.html', {'vendor': vendor, 'products': products,
    'items':items})

e_commerce/templates/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

	<!--main area-->
	<main id="main" class="main-site left-sidebar">

		<div class="container">

			<div class="wrap-breadcrumb"> 
				<ul>
					<li class="item-link"><a href="#" class="link">home</a></li>
					<li class="item-link"><span>login</span></li>
				</ul>
			</div>
			<div class="row">
				<div class="col-lg-6 col-sm-6 col-md-6 col-xs-12 col-md-offset-3">
					<div class=" main-content-area">
						<div class="wrap-login-item ">						
							<div class="login-form form-item form-stl">
								<form name="frm-login" method="POST">
									{% csrf_token %} 
						
									{% if messages %}
									{% for message in messages %}
									<div class="col-sm-12 col-xl-12">
										<div class="alert {{ message.tags }} alert-dismissible" role="alert">
											<strong>{{ message }}!</strong> 
											<button type="button" class="close" data-bs-dismiss="alert"  aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
										  </div>
									</div>
									{% endfor %}
									{% endif %}

									<fieldset class="wrap-title">
										<h3 class="form-title">Log in to your account</h3>										
									</fieldset>
									<fieldset class="wrap-input">
										<label for="frm-login-uname">Email Address:</label>
										<input type="text" id="frm-login-uname" name="email" placeholder="Type your email address">
									</fieldset>
									<fieldset class="wrap-input">
										<label for="frm-login-pass">Password:</label>
										<input type="password" id="frm-login-pass" name="password" placeholder="************">
									</fieldset>
									
									<fieldset class="wrap-input">
										<label class="remember-field">
											<input class="frm-input " name="rememberme" id="rememberme" value="forever" type="checkbox"><span>Remember me</span>
										</label>
										<a class="link-function left-position" href="#" title="Forgotten password?">Forgotten password?</a>
									</fieldset>
									<input type="submit" class="btn btn-submit" value="Login" name="submit">
								</form>
							</div>												
						</div>
					</div><!--end main products area-->		
				</div>
			</div><!--end row-->

		</div><!--end container-->

	</main>
	<!--main area-->

{% endblock %}

e_commerce/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="container" style="margin-top:50px;margin-bottom:50px;">

    <div class="row">
        <div class="col-xs-6 col-md-3">
          {% if request.user.profile_pic  %}
          <a href="#" class="thumbnail">
            <img src="{{request.user.profile_pic.url }}" alt="...">
          </a>
          {% else %}
          <a href="#" class="thumbnail">
            <img src="{% static 'images/products/fashion_04.jpg' %}" alt="...">
          </a>
          {% endif %}
        </div>
       <h1>{{request.user.first_name}} {{ request.user.last_name}}</h1>
       <h3>Email: {{request.user.email}}</h3>
      </div>

      <div class="container">
				<div class="row">
      <li class="col-lg-4 col-md-6 col-sm-6 col-xs-6 ">
        <div class="product product-style-3 equal-elem ">
          <div class="product-info">
          <a href="{% url 'products:add_product_page' %}"   class="btn add-to-cart" >Add Product</a> 
          </div> 
        </div>
      </li>
    </div>
    <div>

      <div class="container">

        <h1>My Product List</h1>

					<div class="row">
            {% if products %}
            <ul class="product-list grid-products equal-container"> 
            {% for product in products %}
                <li class="col-lg-4 col-md-6 col-sm-6 col-xs-6 ">
                  <div class="product product-style-3 equal-elem ">
                    {% if product.image %} 
                    <div class="product-thumnail">
                      <a href="{% url 'products:product_details' product.pk %}" title="T-Shirt Raw Hem Organic Boro Constrast Denim">
                        <figure>
                          <img style="height:250px;" src="{{product.image.url}}" alt="T-Shirt Raw Hem Organic Boro Constrast Denim">
                        </figure>
                      </a>
                    </div>
                    {% endif %} 
                    <div class="product-info">
                     <h3><a href="{% url 'products:product_details' product.pk %}" 
                      class="product-name">{{product.name}}</a> <span>{{product.price}}</span> </h3>

                      <h5>Approved: {{product.is_verified}} </h5> 
                    </div> 

                    <div class="product-info">
                      <a href="{% url 'products:edit_product' product.id %}" class="btn add-to-cart" >Edit Product</a> 
                      </div> 
                  </div>

                </li>

              {% endfor %}
              </ul>
              {% else %}

              <div>
                <h1>You Don't Upload Any Product Yet</h1>
              </div>
              {% endif %}
            </div>
          </div>


          <div class="box">
            <h2 class="is-size-3 mb-4">My orders</h2>
      

                {% if items %}
               
                    <div class="{% if order.fully_paid %}has-background-success-light{% else %}has-background-info-light{% endif %} mb-2 p-4">
                        <div class="columns is-multiline">
                            <!-- <div class="column is-6">
                                <h3 class="is-size-4">#{{ items.customer.id }} - {{ items.customer.first_name }} {{ items.customer.last_name }}</h3>
                            </div> -->
        
                            <div class="column is-12">
                         
                                <table class="table is-fullwidth mt-4">
                                    <thead>
                                        <tr>
                                            <th>Title</th>
                                            <th>Price</th>
                                            <th>Quantity</th>
                                            <th>Paid</th>
                                            <th>Total</th>
                                        </tr>
                                    </thead>
        
                                    <tbody>
                                      {% for order in items %}
                                                <tr>
                                                    <td>{{ order.product.name }}</td>
                                                    <td>${{ order.product.price }}</td>
                                                    <td>{{ order.quantity }}</td>
                                                    <td>{{ order.vendor_paid|yesno:"Yes,No" }}</td>
                                                    <td>${{order.get_total}}</td>  
                                                </tr>  
                                       {% endfor %}  
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
           

                {% else %}
                <div>
                  <h1>You Don't have any order yet</h1>
                </div>

            {% endif %}
        </div>


{% endblock %}






    <div class="box">
        <h1 class="title">Vendor admin - {{ vendor.name }}</h1>

        <strong>My balance: </strong>${{ vendor.get_balance }}<br>
        <strong>My paid amount: </strong>${{ vendor.get_paid_amount }}

        <hr>

        <a href="{% url 'edit_vendor' %}" class="button is-info is-uppercase">Edit</a>
        <a href="{% url 'logout' %}" class="button is-danger is-uppercase">Log out</a>
    </div>

    <div class="box">
        <h2 class="is-size-3 mb-4">My products</h2>

        <a href="{% url 'add_product' %}" class="button is-dark is-uppercase mb-6">Add product</a>

        {% if products %}
            <table class="table is-fullwidth">
                <thead>
                    <tr>
                        <th>Title</th>
                        <th>Price</th>
                        <th>Actions</th>
                    </tr>
                </thead>

                <tbody>
                    {% for product in products %}
                        <tr>
                            <td><a href="{% url 'product' product.category.slug product.slug %}">{{ product.title }}</a></td>
                            <td>${{ product.price }}</td>
                            <td><a href="{% url 'edit_product' product.id %}">Edit</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>You don't have any products yet...</p>
        {% endif %}
    </div>

e_commerce/templates/users/register.html
	{% extends 'base.html' %}
	{% load static %}
	{% block content %}
	
		<!--main area-->
		<main id="main" class="main-site left-sidebar">

			<div class="container">
	
				<div class="wrap-breadcrumb">
					<ul>
						<li class="item-link"><a href="#" class="link">home</a></li>
						<li class="item-link"><span>Register</span></li>
					</ul>
				</div>
				<div class="row">
					<div class="col-lg-6 col-sm-6 col-md-6 col-xs-12 col-md-offset-3">							
						<div class=" main-content-area">
							<div class="wrap-login-item ">
								<div class="register-form form-item ">
									<form  action="#" method="POST" >
										{% csrf_token %}
	
										{% if messages %}
										{% for message in messages %}
										<div class="col-sm-12 col-xl-12">
											<div class="alert {{ message.tags }} alert-dismissible" role="alert">
												<strong>{{ message }}!</strong> 
												<button type="button" class="close" data-bs-dismiss="alert"  aria-label="Close">
													<span aria-hidden="true">&times;</span>
												</button>
											  </div>
										</div>
										{% endfor %}
										{% endif %}		
	
										<fieldset class="wrap-title">
											<h3 class="form-title">Create an account</h3>
											<h4 class="form-subtitle">Personal infomation</h4>
										</fieldset>	
																	
										<fieldset class="wrap-input">
											<label for="frm-reg-lname">First Name*</label>
											<input type="text"  name="firstname" placeholder="First name*">
										</fieldset>
	
										<fieldset class="wrap-input">
											<label for="frm-reg-lname">Last Name*</label>
											<input type="text"  name="lastname" placeholder="Last name*">
										</fieldset>
	
										<fieldset class="wrap-input">
											<label for="frm-reg-email">Phone Number*</label>
											<input type="text"  name="mobilenumber" placeholder="Phone Number">
										</fieldset>
	
										<fieldset class="wrap-input">
											<label for="frm-reg-email">Email Address*</label>
											<input type="email"  name="email" placeholder="Email address">
										</fieldset>
								
										<fieldset class="wrap-title">
											<h3 class="form-title">Login Information</h3>
										</fieldset>
										<fieldset class="wrap-input item-width-in-half left-item ">
											<label for="frm-reg-pass">Password *</label>
											<input type="password"  name="password" placeholder="Password">
										</fieldset>
										<fieldset class="wrap-input item-width-in-half ">
											<label for="frm-reg-cfpass">Confirm Password *</label>
											<input type="password"  name="confirmpassword" placeholder="Confirm Password">
										</fieldset>
										<input type="submit" value="submit" class="btn btn-sign" >
									</form>
								</div>											
							</div>
						</div><!--end main products area-->		
					</div>
				</div><!--end row-->
	
			</div><!--end container-->
	
		</main>
		<!--main area-->
	
	{% endblock %}
	