e_commerce/e_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('homeapp.urls')),
    path('', include('users.urls')),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('admin/', admin.site.urls),  
]

if settings.DEBUG:
    #urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_commerce/orders/urls.py
from django.urls import path
from . import views

app_name ="orders"

urlpatterns = [

#     path('#/',views.cart_detail,name='cart_detail'),
]

e_commerce/products/urls.py
from django.urls import path
from .views import all_products,product_details,updateItem,cart,add_product,edit_product,category,checkout

app_name ="products"

urlpatterns = [
    path('shop/', all_products, name='productPage'), 
    path('update_item/', updateItem, name="update_item"),
    path('cart/', cart, name="cart_page"),
    path('product_details/<int:pk>/',product_details , name='product_details'),  

    path('add_product/', add_product, name="add_product_page"),  
    path('edit-product/<int:pk>/', edit_product, name='edit_product'),

    path('category/<int:pk>/', category, name='category_products'),

    path('checkout/', checkout, name="checkout"),
]  

e_commerce/users/urls.py
from django.urls import path
from users.views import RegisterView,LogInView,LogOutView,userProfile

app_name ="users"

urlpatterns = [
    path('login/', LogInView, name='loginPage'),  
    path('sign-up/', RegisterView, name='registerPage'),
    # path('sign-out/', LogOutView.as_view(), name='logoutPage'),
    path('sign-out/', LogOutView, name='logoutPage'),
    path('my-profile/', userProfile, name='profilePage'),
] 

e_commerce/orders/models.py
from django.db import models
from products.models import Product
from users.models import Accounts

class Order(models.Model):
	customer = models.ForeignKey(Accounts, on_delete=models.SET_NULL, null=True, blank=True)
	date_ordered = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False)
	transaction_id = models.CharField(max_length=100, null=True)

	def __str__(self):
		return str(self.customer.email) 
		
	# @property
	# def shipping(self):
	# 	shipping = False
	# 	orderitems = self.orderitem_set.all()
	# 	for i in orderitems:
	# 		if i.product.digital == False:
	# 			shipping = True
	# 	return shipping

	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total 

	@property
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total 

class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	quantity = models.IntegerField(default=0, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True) 

	@property 
	def get_total(self):
		total = self.product.price * self.quantity
		return total

	def __str__(self):
        	return str(self.product.name) + str(self.order.customer.email)


class ShippingAddress(models.Model):
	customer = models.ForeignKey(Accounts, on_delete=models.SET_NULL, null=True)
	order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=200, null=False)
	city = models.CharField(max_length=200, null=False)
	state = models.CharField(max_length=200, null=False)
	zipcode = models.CharField(max_length=200, null=False) 
	date_added = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.address
    

 

e_commerce/orders/views.py
from django.shortcuts import render, redirect

e_commerce/templates/orders/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

	<!--main area-->
	<main id="main" class="main-site">

		<div class="container">

			<div class="wrap-breadcrumb">
				<ul>
					<li class="item-link"><a href="#" class="link">home</a></li>
					<li class="item-link"><span>login</span></li>
				</ul>
			</div>
			<div class=" main-content-area">

				<div class="wrap-iten-in-cart">
					<h3 class="box-title">Products Name</h3>
					<ul class="products-cart"> 

                        {% for item in items %}  
						<li class="pr-cart-item"> 
							<div class="product-image">
								<figure><img src="{{item.product.image.url}}" alt=""></figure>
							</div>
							<div class="product-name">
								<a class="link-to-product" href="#">{{item.product.name}}</a> 
							</div>
							<div class="price-field produtc-price">
								<p class="price">{{item.product.price|floatformat:2}}</p>
							</div>
							
							<div class="quantity">
								<div class="quantity-input">
		
									<a class="btn btn-increase add-to-cart" id="cartdata" data-action="add"   data-product="{{item.product.id}}" data-action="add" href="#"></a>
									<input type="text" name="product-quatity" value="{{item.quantity}}" data-max="120" pattern="[0-9]*" >	
									<a class="btn btn-reduce add-to-cart" id="cartdata" data-action="remove"  data-product="{{item.product.id}}" data-action="remove" href="#"></a>								
								</div>
							</div> 

							<div class="price-field sub-total">  
                                <p class="price">{{item.get_total|floatformat:2}}</p>
                            </div>

							{% comment %} <div class="delete"> 
								<a href="#" class="btn "  title="">
									<span>Delete from your cart</span>
									<i  id="cartdata" data-product="{{item.product.id}}" data-action="delete" class="fa fa-times-circle add-to-cart" aria-hidden="true"></i>
								</a>
							</div> {% endcomment %}

						</li>
                        {% endfor %}
                        
					</ul>
				</div> 

				<div class="summary">
					<div class="order-summary">
						<h4 class="title-box">Order Summary</h4>
						<p class="summary-info"><span class="title">Number of Item</span><b class="index">{{cartItems}}</b></p>
						<p class="summary-info"><span class="title">Subtotal</span><b class="index">${{order.get_cart_total}}</b></p>
						<p class="summary-info"><span class="title">Shipping</span><b class="index">Free Shipping</b></p>
						<p class="summary-info total-info "><span class="title">Total</span><b class="index">{{order.get_cart_total|floatformat:2}}</b></p>
					</div>
					<div class="checkout-info">
						<a class="btn btn-checkout" href="{% url 'products:checkout' %}">Check out</a>
						<a class="link-to-shop" href="{% url 'products:productPage' %}">Continue Shopping<i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a>
					</div>
					{% comment %} <div class="update-clear">
						<a class="btn btn-clear" href="#">Clear Shopping Cart</a> 
						<a class="btn btn-update" href="#">Update Shopping Cart</a>
					</div> {% endcomment %}
				</div>

				<div class="wrap-show-advance-info-box style-1 box-in-site">
					<h3 class="title-box">Most Viewed Products</h3>
					<div class="wrap-products">
						<div class="products slide-carousel owl-carousel style-nav-1 equal-container" data-items="5" data-loop="false" data-nav="true" data-dots="false" data-responsive='{"0":{"items":"1"},"480":{"items":"2"},"768":{"items":"3"},"992":{"items":"3"},"1200":{"items":"5"}}' >

				
							{% for product in products %}
							<div class="product product-style-2 equal-elem "> 
								<div class="product-thumnail">
									<a href="{% url 'products:product_details' product.pk %}" title="T-Shirt Raw Hem Organic Boro Constrast Denim">
										<figure><img src="{{product.image.url}}" width="214" height="214" alt="T-Shirt Raw Hem Organic Boro Constrast Denim"></figure>
									</a>
									<div class="group-flash">
										<span class="flash-item new-label">new</span>
										<span class="flash-item sale-label">sale</span>
									</div>
									<div class="wrap-btn">
										<a href="#" class="function-link">quick view</a>
									</div>
								</div>
								<div class="product-info">
									<a href="{% url 'products:product_details' product.pk %}" class="product-name"><span>{{product.name}}</span></a>
									<div class="wrap-price"><ins><p class="product-price">${{product.price}}</p></ins> <del><p class="product-price">${{product.price}}</p></del></div>
								</div>
							</div>
							{% endfor %}

					


						</div>
					</div><!--End wrap-products-->
				</div>

			</div><!--end main content area-->
		</div><!--end container-->

	</main>
	<!--main area-->

{% endblock %}

e_commerce/templates/orders/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
	<!--main area-->
	<main id="main" class="main-site">
		<div class="container">
			<div class="row">
				<div class="col-md-6">

					<div class="wrap-address-billing">
						<h3 class="box-title">Billing Address</h3>
						<form action="#" method="POST" enctype="multipart/form-data" name="frm-billing">
							{% csrf_token %} 
							<p class="row-in-form">
								<label for="add">Address:</label>
								<input id="add" type="text" name="address" value="" placeholder="Street at apartment number">
							</p>
							<p class="row-in-form">
								<label for="country">State<span>*</span></label>
								<input id="country" type="text" name="state" value="" placeholder="United States">
							</p>
							<p class="row-in-form">
								<label for="zip-code">Postcode / ZIP:</label>
								<input id="zip-code" type="number" name="zipcode" value="" placeholder="Your postal code">
							</p>
							<p class="row-in-form">
								<label for="city">Town / City<span>*</span></label>
								<input id="city" type="text" name="city" value="" placeholder="City name">
							</p>

							<div class="summary-item payment-method">
								
								<button class="btn btn-medium" type="submit">Place order now</button>
							</div>
		
						</form>
					</div>

				</div>

				<div class="col-md-6">

					<div class="box-element">
						<a  class="btn btn-outline-dark" href="">&#x2190; Back to Cart</a>
						<hr>
						<h3>Order Summary</h3>
						<hr>
						{% for item in items %}
						<div class="cart-row">
							<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
							<div style="flex:2"><p>{{item.product.name}}</p></div>
							<div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
							<div style="flex:1"><p>x{{item.quantity}}</p></div>
						</div>
						{% endfor %}
						<h5>Items:   {{order.get_cart_items}}</h5>
						<h5>Total:   ${{order.get_cart_total|floatformat:2}}</h5>
					</div>
				</div>
			</div>


		</div>

	</main>

	<!--main area-->

{% endblock %}

e_commerce/templates/orders/newCart.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<a  class="btn btn-outline-dark" href="{% url 'store' %}">&#x2190; Continue Shopping</a>

				<br>
				<br>
				<table class="table">
					<tr>
						<th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
						<th><h5>Total:<strong> ${{order.get_cart_total|floatformat:2}}</strong></h5></th>
						<th>
							<a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'checkout' %}">Checkout</a>
						</th>
					</tr>
				</table>

			</div>

			<br>
			<div class="box-element">
				<div class="cart-row">
					<div style="flex:2"></div>
					<div style="flex:2"><strong>Item</strong></div>
					<div style="flex:1"><strong>Price</strong></div>
					<div style="flex:1"><strong>Quantity</strong></div>
					<div style="flex:1"><strong>Total</strong></div>
				</div>
				{% for item in items %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.imageURL}}"></div>
					<div style="flex:2"><p>{{item.product.name}}</p></div>
					<div style="flex:1"><p>${{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1">
						<p class="quantity">{{item.quantity}}</p>
						<div class="quantity">
							<img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static  'images/arrow-up.png' %}">
					
							<img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static  'images/arrow-down.png' %}">
						</div>
					</div>
					<div style="flex:1"><p>${{item.get_total|floatformat:2}}</p></div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock content %}